\STATE 1. Compute clustering algorithm (e.g., $K$-means clustering) for different values of $K$.
For instance, by varying $K$ from 1 to 10 clusters.
\STATE 2. For each $K$, calculate the total within-cluster sum of square $(wss)$.
\STATE 3. Plot the curve of $wss$ according to the number of clusters $K$.
\STATE 4. The location of a bend (knee) in the plot is generally considered
as an indicator of the appropriate number of clusters.

\endinput
