\STATE 1. Compute clustering algorithm (e.g., $K$-means clustering) for different values of $K$.
For instance, by varying $K$ from 1 to 10 clusters.
\STATE 2. For each $K$, calculate the average silhouette of observations $(avg.sil)$.
\STATE 3. Plot the curve of $avg.sil$ according to the number of clusters $K$.
\STATE 4. The location of the maximum is considered as the appropriate number of clusters.

\endinput
